apiVersion: batch/v1
kind: Job
metadata:
  name: ${SERVICE_NAME}
spec:
  parallelism: 1
  completions: 1
  ttlSecondsAfterFinished: 5
  template:
    metadata:
      labels:
        app: telemetrygen
    spec:
      containers:
      - name: telemetrygen
        image: ttl.sh/isracosa:latest
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NODE
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        args:
          - "traces"
          - "--otlp-insecure"
          - "--child-spans=10"
          - "--rate=10"
          - "--traces=100"
          - "--otlp-http"
          - "--otlp-endpoint=$(NODE):4318"
          - "--service=${SERVICE_NAME}"
      restartPolicy: Never
  backoffLimit: 0
