apiVersion: batch/v1
kind: Job
metadata:
  name: telemetrygen-job
spec:
  parallelism: 100
  completions: 100
  template:
    metadata:
      labels:
        app: telemetrygen
    spec:
      containers:
      - name: telemetrygen
        image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:latest
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NODE
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "$(NODE):4317"
        args:
          - "traces"
          - "--otlp-insecure"
          - "--rate=500"
          - "--duration=30m"
          - "--service" # This sumulates a different service for each pod
          - "$(POD_NAME)"
      restartPolicy: Never
  backoffLimit: 0